### PUT new patient data
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Neshi Viray",
  "email": "neshi.viray@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}
###